### ISSUE TITLE
No line number in source path

### ISSUE THREAD

**Issue by dakra** [brightin/pottery#4]
Pottery writes the filename in the pot file like:
```
#: src/foo/bar.clj
msgid "foo"
msgstr ""
```

But to jump to the specific location you also need the line number (e.g. Emacs po-mode doesn't jump at all to the source if the line number is missing).
So it should look like:
```
#: src/foo/bar.clj:23
msgid "foo"
msgstr ""
```

Thanks and thanks for this library.
I'm a bit surprised at the miserable state of i18n/gettext in Clojure(Script), does nobody do Clojure projects with many languages? (rant over ;)

**Comment by stefanroex** [comment]
Thank for the issue. Wasn't aware of po-mode, we're using currently using poedit. I agree that adding a line-number is useful and I'll try to create a PR in the next couple of weeks. I'll keep you posted!

**Comment by yannvanhalewyn** [comment]
Hi! I looked into this a bit. There currently isn't an easy way to keep track of line numbers as we just, very simply, `slurp` the file and read it as Clojure data. One approach would be to use something like [rewrite-clj](https://github.com/clj-commons/rewrite-clj/) instead which I believe keeps track of the position of expressions. While I do see the benefits to this feature, it would take a bit of effort so we won't implement this for now. That being said we are open for a PR if you want to give it a go!

Reading source files is done here: https://github.com/brightin/pottery/blob/master/src/pottery/scan.clj#L20-L21

**Comment by dakra** [comment]
No worries.
This is obviously a very minor thing and not really important.
Maybe I'll create a PR in the future but that could take a while.

Thanks for looking into it and thanks for pottery.

**Comment by yannvanhalewyn** [comment]
You're welcome! ❤️
