### ISSUE TITLE
Some expressions in .cljc files go undetected

### ISSUE THREAD

**Issue by borkdude** [brightin/pottery#6]
There are multiple issues with detecting expressions in .cljc files.

1. The JVM Clojure reader that is built into Clojure doesn't ignore `:clj` branches, even if you specify `:features #{:cljs}`.

This example from a `.cljc` file should probably return `(tr "bar")` if you're looking for the ClojureScript expression. Currently only `(tr "foo")` is returned:

``` clojure
(read-string {:read-cond :allow :features #{:cljs}} "#?(:clj (tr \"foo\") :cljs (tr \"bar\"))")
;;=> (tr "foo")
```

This is because the built-in Clojure reader always prioritizes `:clj` branches, no matter what you specify.

A solution to this would be to use edamame or tools.reader which does let you limit the feature you would like to read:

``` clojure
user=> (require '[edamame.core :as e])
nil
user=> (e/parse-string "#?(:clj (tr \"foo\") :cljs (tr \"bar\"))" {:read-cond :allow :features #{:cljs}})
(tr "bar")
```

You would have to parse each string for each feature (`:clj`, `:cljs`) to properly pull out the expressions for each language (this is what I do in clj-kondo as well, I believe there is no way to parse a .cljc file once to properly analyze it for each individual language).

2a. The setting `:read-cond :preserve` returns reader conditional objects which then cause expressions not to be matched properly:

``` clojure
user=> (scan/extract scan/default-extractor (read-string {:read-cond :preserve :features #{:cljs}} "#?(:clj (tr \"foo\") :cljs (tr \"bar\"))"))
nil
```

2b. The setting `:read-cond :preserve` can result in invalid expressions:

``` clojure
user=> (read-string {:read-cond :preserve :features #{:clj}} "{#?@(:clj [:a :b])}")
Execution error at user/eval1570 (REPL:1).
Map literal must contain an even number of forms
user=> (read-string {:read-cond :allow :features #{:clj}} "{#?@(:clj [:a :b])}")
{:a :b}
```

Proposal:

- Use edamame or tools.reader as a Clojure reader
- Don't use `:read-cond :preserve` but parse every file separately for each language feature

I have a branch where all of this already works:

https://github.com/brightin/pottery/compare/master...nextjournal:pottery:features-wip

The best place to start reading this would be the tests.

**Comment by borkdude** [comment]
If you agree with my approach, @stefanroex, I'd be happy to create a PR and we can address any concerns.

**Comment by stefanroex** [comment]
@borkdude I agree with both proposals and I'm impressed that you got this working 👍. You even made sure that functions like `pottery.scan/extract` are backwards compatible.

For our projects we opted to not use translatable strings in reader-conditionals. But I fully expect that some translatable strings did end up in reader conditionals through the years, it's something easy to forget. Nice that we don't need to think about that anymore.

Feel free to open a PR 👍.
